// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4BspBBeQ-LjYbgf1dEIrY839pao3IvU8',
    appId: '1:393324360545:web:4766d8d04620333126cb20',
    messagingSenderId: '393324360545',
    projectId: 'hopin-8eceb',
    authDomain: 'hopin-8eceb.firebaseapp.com',
    storageBucket: 'hopin-8eceb.firebasestorage.app',
    measurementId: 'G-6X9Q2JLJ2D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAm-txPJRrQT4lCWqvPDOCv2hIdIlVQVY4',
    appId: '1:393324360545:android:6e122b3d2c0776e626cb20',
    messagingSenderId: '393324360545',
    projectId: 'hopin-8eceb',
    storageBucket: 'hopin-8eceb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqYwXWKKOActuoqoIPMjLHZKn4fg1MW-w',
    appId: '1:393324360545:ios:b947755eb547312826cb20',
    messagingSenderId: '393324360545',
    projectId: 'hopin-8eceb',
    storageBucket: 'hopin-8eceb.firebasestorage.app',
    iosBundleId: 'com.example.hopin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqYwXWKKOActuoqoIPMjLHZKn4fg1MW-w',
    appId: '1:393324360545:ios:b947755eb547312826cb20',
    messagingSenderId: '393324360545',
    projectId: 'hopin-8eceb',
    storageBucket: 'hopin-8eceb.firebasestorage.app',
    iosBundleId: 'com.example.hopin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD4BspBBeQ-LjYbgf1dEIrY839pao3IvU8',
    appId: '1:393324360545:web:cc506241764d4aae26cb20',
    messagingSenderId: '393324360545',
    projectId: 'hopin-8eceb',
    authDomain: 'hopin-8eceb.firebaseapp.com',
    storageBucket: 'hopin-8eceb.firebasestorage.app',
    measurementId: 'G-EQYWPDVCV8',
  );
}
